Add multi select mode for choose cmd

diff --git a/.local/bin/choose b/.local/bin/choose
--- a/.local/bin/choose
+++ b/.local/bin/choose
@@ -7,7 +7,6 @@ source "$BASH_LIB_DIR/args.sh"
 source "$BASH_LIB_DIR/utils.sh"
 
 readonly ERR_NO_VALUES=2
-readonly ERR_CANCELED=3
 
 help() {
   cat <<-EOT
@@ -20,20 +19,21 @@ help() {
 		Options:
 		  -p <prompt>   Message to print as a prompt.
 		  -d <default>  Default value to print if no values are available.
-		  -i            Read lines from stdin as values.
-		  -0            Expect stdin values to be separated by null character.
-		  -b            Use basic interface instead of fzf.
+		  -m            Enable selection of multiple values.
+		  -i            Read values from standard input.
+		  -z            Read values delimited by NUL character instead of newline.
+		  -Z            Print results delimited by NUL character instead of newline.
+		  -b            Force basic interface instead of fzf.
 		  -h            Display this help.
 
 		Value:
 		  Zero or more values to select from.
-      Ignored when the -i option is used.
+		  Ignored when the -i option is used.
 
 		Exit status:
 		  0  Normal exit.
 		  1  Error.
 		  2  No values.
-		  3  Canceled by user.
 
 		Links:
 		  fzf  https://github.com/junegunn/fzf
@@ -43,12 +43,14 @@ help() {
 init() {
   local opt
 
-  while getopts "p:d:i0bh" opt; do
+  while getopts ":p:d:mizZbh" opt; do
     case "$opt" in
       p) prompt=$OPTARG ;;
       d) default=$OPTARG ;;
+      m) multi=true ;;
       i) stdin=true ;;
-      0) null=true ;;
+      z) null_in=true ;;
+      Z) null_out=true ;;
       b) basic=true ;;
       h) help; exit ;;
       *) die_invalid_opt "$opt" ;;
@@ -60,7 +62,7 @@ init() {
 }
 
 run() {
-  local result=
+  local results=()
 
   if [[ $basic = false ]] && is_command fzf; then
     fzf_mode
@@ -68,46 +70,44 @@ run() {
     basic_mode
   fi
 
-  if [[ $result ]]; then
-    echo "$result"
-  elif [[ $default ]]; then
-    echo "$default"
+  if [[ ${#results[@]} -eq 0 ]]; then
+    if [[ $default ]]; then
+      results=("$default")
+    else
+      exit $ERR_NO_VALUES
+    fi
+  fi
+
+  if [[ $null_out = true ]]; then
+    printf "%s\0" "${results[@]}"
   else
-    exit $ERR_NO_VALUES
+    printf "%s\n" "${results[@]}"
   fi
 }
 
 fzf_mode() {
-  local opts=("--layout=reverse" "--select-1" "--exact")
+  local opts=("--select-1" "--exit-0" "--print0")
 
   if [[ $stdin = true ]]; then
     export FZF_DEFAULT_COMMAND=cat # To force reading from stdin
-  else
+    [[ $null_in = true ]] && opts+=("--read0")
+  elif [[ ${#values[@]} -gt 0 ]]; then
     exec < <(printf "%s\0" "${values[@]}")
-  fi
-
-  if [[ $stdin = false || $null = true ]]; then
     opts+=("--read0")
+  else
+    exec </dev/null # To fail fast using the --exit-0 option
   fi
 
-  if [[ $prompt ]]; then
-    opts+=("--prompt=$prompt ")
-  fi
+  [[ $multi = true ]] && opts+=("--multi")
+  [[ $prompt ]] && opts+=("--prompt=$prompt ")
 
-  local error=
-  result=$(fzf "${opts[@]}") || error=$?
-
-  if [[ $error -eq 130 ]]; then
-    exit $ERR_CANCELED
-  elif [[ $error -gt 1 ]]; then
-    exit "$ERR_GENERIC"
-  fi
+  mapfile -td '' results < <(fzf "${opts[@]}")
 }
 
 basic_mode() {
   if [[ $stdin = true ]]; then
-    if [[ $null = true ]]; then
-      mapfile -t -d '' values
+    if [[ $null_in = true ]]; then
+      mapfile -td '' values
     else
       mapfile -t values
     fi
@@ -116,20 +116,32 @@ basic_mode() {
   fi
 
   if [[ ${#values[@]} -eq 1 ]]; then
-    result=${values[0]}
+    results=("${values[0]}")
   elif [[ ${#values[@]} -gt 1 ]]; then
-    [[ $prompt ]] && echo "$prompt" >&2
-    select result in "${values[@]}"; do
-      [[ $result ]] && break
-    done || exit $ERR_CANCELED
+    local choice
+    while true; do
+      [[ $prompt ]] && echo "$prompt"
+      select choice in "${values[@]}"; do
+        if [[ $choice ]]; then
+          results+=("$choice")
+          if [[ $multi = true ]]; then
+            mapfile -td '' values < <(remove_value "$choice" "${values[@]}")
+          fi
+          break
+        fi
+      done || break
+      [[ $multi = false || ${#values[@]} -eq 0 ]] && break
+    done
   fi
-}
+} >&2
 
 main() {
   local prompt=
   local default=
+  local multi=false
   local stdin=false
-  local null=false
+  local null_in=false
+  local null_out=false
   local basic=false
   local values
 
