Move core functions to core.sh

diff --git a/.local/bin/find-npm-dirs b/.local/bin/find-npm-dirs
--- a/.local/bin/find-npm-dirs
+++ b/.local/bin/find-npm-dirs
@@ -2,7 +2,7 @@
 
 set -euo pipefail
 
-source "$BASH_LIB_DIR/utils.sh"
+source "$BASH_LIB_DIR/core.sh"
 source "$BASH_LIB_DIR/args.sh"
 
 print_help() {
@@ -23,7 +23,7 @@ print_help() {
 }
 
 set_path() {
-  [[ -d $1 ]] || die "'$1' is not a directory!"
+  [[ -d $1 ]] || die "'$1' is not a directory"
   path=$1
 }
 
@@ -58,7 +58,7 @@ find_npm_dirs() {
   mapfile -t expression < <(get-find-expression --lines --ignore-non-sources)
   mapfile -t npm_dirs < <(find . "${expression[@]}" -name package.json -exec dirname {} \;)
 
-  [[ ${#npm_dirs[@]} -gt 0 ]] || die "Unable to find any package.json!"
+  [[ ${#npm_dirs[@]} -gt 0 ]] || die "unable to find any package.json"
 
   if [[ ${#npm_dirs[@]} -gt 1 && $select_one == true ]]; then
     print-selection "${npm_dirs[@]}"
diff --git a/.local/bin/npm-run-script b/.local/bin/npm-run-script
--- a/.local/bin/npm-run-script
+++ b/.local/bin/npm-run-script
@@ -2,8 +2,9 @@
 
 set -euo pipefail
 
-source "$BASH_LIB_DIR/utils.sh"
+source "$BASH_LIB_DIR/core.sh"
 source "$BASH_LIB_DIR/args.sh"
+source "$BASH_LIB_DIR/utils.sh"
 
 print_help() {
   cat <<-EOT
@@ -25,7 +26,7 @@ print_help() {
 
 set_rerun_delay() {
   # shellcheck disable=SC2015
-  is_integer "$1" && [[ $1 -ge 0 ]] || die "Invalid rerun delay '$1'!"
+  is_integer "$1" && [[ $1 -ge 0 ]] || die "invalid rerun delay '$1'"
   rerun_delay=$1
 }
 
@@ -55,7 +56,7 @@ process_args() {
 }
 
 npm_run_any() {
-  [[ -f package.json ]] || die "No package.json in the current directory!"
+  [[ -f package.json ]] || die "no package.json in the current directory"
 
   local available_scripts
   local target_script
@@ -70,13 +71,12 @@ npm_run_any() {
   done
 
   if [[ -z $target_script ]]; then
-    die "package.json has none of [$(join_values ", " "${scripts[@]}")] scripts!"
+    die "package.json has none of [$(join_values ", " "${scripts[@]}")] scripts"
   fi
 
   while ! npm run "$target_script"; do
     [[ $rerun_on_failure = true ]] || break
-    echo_error
-    echo_error "package.json $target_script script unexpectedly crashed!"
+    printf "\npackage.json %s script unexpectedly crashed!\n" "$target_script" >&2
     interactive-sleep "$rerun_delay" "Script will automatically rerun" || true
   done
 }
