Merge init/run functions into main

diff --git a/.local/bin/isleep b/.local/bin/isleep
--- a/.local/bin/isleep
+++ b/.local/bin/isleep
@@ -31,13 +31,7 @@ help() {
 	EOT
 }
 
-set_duration() {
-  # shellcheck disable=SC2015
-  is_integer "$1" && [[ $1 -ge 0 ]] || die "invalid duration '$1'"
-  duration=$1
-}
-
-init() {
+main() {
   local opt
 
   while getopts ":h" opt; do
@@ -48,17 +42,14 @@ init() {
   done
 
   shift $((OPTIND - 1))
+  [[ $# -eq 0 ]] && die_missing_arg
 
-  if [[ $# -ge 1 ]]; then
-    set_duration "$1"
-    message=${2:-}
-  else
-    die_missing_arg
-  fi
-}
+  # shellcheck disable=SC2015
+  is_integer "$1" && [[ $1 -ge 0 ]] || die "invalid duration '$1'"
 
-run() {
+  local duration=$1
   local time_left=$duration
+  local message=${2:-}
   local error=$ERR_OK
 
   tput sc # Save the cursor position.
@@ -84,14 +75,6 @@ run() {
   tput cnorm || true # Set the cursor to its normal state (may not be supported by terminal).
 
   exit $error
-}
-
-main() {
-  local duration
-  local message
-
-  init "$@"
-  run
 }
 
 main "$@"
diff --git a/.local/bin/npmrs b/.local/bin/npmrs
--- a/.local/bin/npmrs
+++ b/.local/bin/npmrs
@@ -24,34 +24,26 @@ help() {
 	EOT
 }
 
-set_rerun_delay() {
-  # shellcheck disable=SC2015
-  is_integer "$1" && [[ $1 -ge 0 ]] || die "invalid rerun delay '$1'"
-  rerun_delay=$1
-}
-
-init() {
+main() {
+  local rerun_on_failure=false
+  local rerun_delay=30
   local opt
 
   while getopts ":rd:h" opt; do
     case "$opt" in
       r) rerun_on_failure=true ;;
-      d) set_rerun_delay "$OPTARG" ;;
+      d) # shellcheck disable=SC2015
+         is_integer "$OPTARG" && [[ $OPTARG -ge 0 ]] || die "invalid rerun delay '$OPTARG'"
+         rerun_delay=$OPTARG ;;
       h) help; exit ;;
       *) die_invalid_opt "$opt" ;;
     esac
   done
 
   shift $((OPTIND - 1))
+  [[ $# -eq 0 ]] && die_missing_arg
 
-  if [[ $# -ge 1 ]]; then
-    scripts=("$@")
-  else
-    die_missing_arg
-  fi
-}
-
-run() {
+  local scripts=("$@")
   local available_scripts
   local target_script=
 
@@ -73,15 +65,6 @@ run() {
     printf "\npackage.json %s script unexpectedly crashed!\n" "$target_script" >&2
     isleep "$rerun_delay" "Restart" || true
   done
-}
-
-main() {
-  local rerun_on_failure=false
-  local rerun_delay=30
-  local scripts
-
-  init "$@"
-  run
 }
 
 main "$@"
diff --git a/.local/bin/progbar b/.local/bin/progbar
--- a/.local/bin/progbar
+++ b/.local/bin/progbar
@@ -25,75 +25,44 @@ help() {
 	EOT
 }
 
-set_value() {
-  # shellcheck disable=SC2015
-  is_integer "$1" && [[ $1 -ge 0 ]] || die "Invalid value '$1'"
-  value=$1
-}
-
-set_max_value() {
-  # shellcheck disable=SC2015
-  is_integer "$1" && [[ $1 -ge 1 ]] || die "invalid max value '$1'"
-  max_value=$1
-}
-
-set_width() {
-  # shellcheck disable=SC2015
-  is_integer "$1" && [[ $1 -ge 1 ]] || die "invalid width '$1'"
-  width=$1
-}
-
-set_fg_char() {
-  # shellcheck disable=SC2015
-  is_character "$1" || die "invalid foreground character '$1'"
-  fg_char=$1
-}
-
-set_bg_char() {
-  is_character "$1" || die "invalid background character '$1'"
-  bg_char=$1
-}
-
-init() {
-  local opt
-
-  while getopts ":w:m:f:b:h" opt; do
-    case "$opt" in
-      w) set_width "$OPTARG" ;;
-      m) set_max_value "$OPTARG" ;;
-      f) set_fg_char "$OPTARG" ;;
-      b) set_bg_char "$OPTARG" ;;
-      h) help; exit ;;
-      *) die_invalid_opt "$opt" ;;
-    esac
-  done
-
-  shift $((OPTIND - 1))
-
-  if [[ $# -ge 1 ]]; then
-    set_value "$1"
-  else
-    die_missing_arg
-  fi
-}
-
-run() {
-  local fg_width=$(( width * value / max_value ))
-  local bg_width=$(( width - fg_width ))
-
-  repeat_value "$fg_width" "$fg_char"
-  repeat_value "$bg_width" "$bg_char"
-}
-
 main() {
   local value
   local max_value=100
   local width=80
   local fg_char="#"
   local bg_char="-"
+  local opt
 
-  init "$@"
-  run
+  while getopts ":w:m:f:b:h" opt; do
+    case "$opt" in
+      w) # shellcheck disable=SC2015
+         is_integer "$OPTARG" && [[ $OPTARG -ge 1 ]] || die "invalid width '$OPTARG'"
+         width=$OPTARG ;;
+      m) # shellcheck disable=SC2015
+         is_integer "$OPTARG" && [[ $OPTARG -ge 1 ]] || die "invalid max value '$OPTARG'"
+         max_value=$OPTARG ;;
+      f) # shellcheck disable=SC2015
+         is_character "$OPTARG" || die "invalid foreground character '$OPTARG'"
+         fg_char=$OPTARG ;;
+      b) is_character "$OPTARG" || die "invalid background character '$OPTARG'"
+         bg_char=$OPTARG ;;
+      h) help; exit ;;
+      *) die_invalid_opt "$opt" ;;
+    esac
+  done
+
+  shift $((OPTIND - 1))
+  [[ $# -eq 0 ]] && die_missing_arg
+
+  # shellcheck disable=SC2015
+  is_integer "$1" && [[ $1 -ge 0 ]] || die "Invalid value '$1'"
+  local value=$1
+
+  local fg_width=$(( width * value / max_value ))
+  local bg_width=$(( width - fg_width ))
+
+  repeat_value "$fg_width" "$fg_char"
+  repeat_value "$bg_width" "$bg_char"
 }
 
 main "$@"
